version: "3.9"

services:
  football:
    build:
      context: ./
      dockerfile: Dockerfile
    image: football-dev:latest
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    command: tail -f /dev/null
    environment:
      POSTGRES_HOST: football-db
      POSTGRES_PORT: 5432
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - ./.volumes/football/_build:/app/_build

  football-db:
    image: postgres:14.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_HOST: football-db
      POSTGRES_DB: football
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football
    volumes:
      - ./.volumes/football-db/data:/var/lib/postgresql/data
