version: "3.9"

services:
  football:
    build:
      context: ./
      dockerfile: Dockerfile
    image: football-dev:latest
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    command: tail -f /dev/null
    # command: mix serve
    environment:
      POSTGRES_HOST: football-db
      POSTGRES_PORT: 5432
    ports:
      - 4000:4000
    depends_on:
      - loki
      - football-db
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'
    volumes:
      - .:/app
      - ./.volumes/football/_build:/app/_build
      - ./.volumes/football/deps:/app/deps

  football-db:
    image: postgres:14.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_HOST: football-db
      POSTGRES_DB: football
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football
    volumes:
      - ./.volumes/database/data:/var/lib/postgresql/data

  loki:
    image: grafana/loki:2.4.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./.docker/loki/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - ./.docker/grafana/:/etc/grafana/provisioning/
    ports:
      - 3000:3000

  tempo:
    image: grafana/tempo:1.3.1
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./.docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - 8000:8000 # tempo
      - 55681:55681 # otlp http
